image:
  tag: v23.1.3
license_secret_ref:
  secret_name: redpanda-license
  secret_key: license
tolerations:
  - key: bigboy
    operator: Exists
commonLabels:
  ec.ai/environment: dev
  ec.ai/team: cora
  ec.ai/component_group: cora-service
  ec.ai/component: redpanda
  ec.ai/sub_component: k8s-deployment
  ec.ai/shared: "false"
  ec.ai/technical_owner: rluckie
  ec.ai/contract: ec
  ec.ai/managed_by: gitops
  ec.ai/data_classification: internal
rackAwareness:
  enabled: true
  nodeAnnotation: topology.kubernetes.io/zone
console:
  enabled: false
tls:
  enabled: false
resources:
  cpu:
    cores: 24
    overprovisioned: false
  memory:
    container:
      max: 192Gi
storage:
  persistentVolume:
    enabled: true
    size: 1500Gi
    storageClass: ssd-xfs
  tieredConfig:
    cloud_storage_api_endpoint: storage.googleapis.com
    cloud_storage_bucket: ec-cora-redpanda-golf-tieredstorage
    cloud_storage_cache_size: 53687091200
    cloud_storage_credentials_source: gcp_instance_metadata
    cloud_storage_enable_remote_read: true
    cloud_storage_enable_remote_write: true
    cloud_storage_enabled: true
    cloud_storage_region: us
  tieredStoragePersistentVolume:
    enabled: true
    storageClass: ssd-xfs
logging:
  logLevel: info
  usageStats:
    enabled: false
    organization: ec.ai
    clusterId: dev-golf
statefulset:
  replicas: 5
  priorityClassName: shared-high-preempting
  tolerations:
    - key: bigboy
      operator: Exists
  startupProbe:
    initialDelaySeconds: 1
    failureThreshold: 120
    periodSeconds: 10
  livenessProbe:
    initialDelaySeconds: 10
    failureThreshold: 300
    periodSeconds: 10
  readinessProbe:
    initialDelaySeconds: 1
    failureThreshold: 3
    periodSeconds: 10
    successThreshold: 1
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: cloud.google.com/gke-spot
              operator: DoesNotExist
            - key: cloud.google.com/gke-os-distribution
              operator: In
              values:
                - ubuntu
            - key: cloud.google.com/machine-family
              operator: In
              values:
                - n2
            - key: cloud.google.com/gke-ephemeral-storage-local-ssd
              operator: In
              values:
                - "true"
            - key: node.kubernetes.io/instance-type
              operator: In
              values:
                - n2-highmem-64
  initContainers:
    tuning:
      resources:
        limits:
          cpu: 1
          memory: 500Mi
        requests:
          cpu: 1
          memory: 500Mi
    setTieredStorageCacheDirOwnership:
      resources:
        limits:
          cpu: 1
          memory: 500Mi
        requests:
          cpu: 1
          memory: 500Mi
    configurator:
      resources:
        limits:
          cpu: 1
          memory: 500Mi
        requests:
          cpu: 1
          memory: 500Mi
serviceAccount:
  create: true
  name: cora-redpanda-golf
  annotations:
    iam.gke.io/gcp-service-account: cora-redpanda-golf@elementalcognition-app-dev.iam.gserviceaccount.com
rbac:
  enabled: true
listeners:
  kafka:
    port: 9092
    external:
      default:
        enabled: true
        port: 9094
        advertisedPorts:
          - 9094
external:
  domain: dev.corp.ec.ai
  enabled: true
  type: null
config:
  cluster:
    log_cleanup_policy: compact,delete
    log_compression_type: none
    partition_autobalancing_mode: continuous
    retention_local_target_bytes_default: 805306368
    retention_local_target_ms_default: 21600000
  tunable:
    log_segment_size: 128MiB # 128 Mi (helm: 128Mi, docs: 128 Mi)
    log_segment_size_min: 16MiB #  16 Mi (helm: 16Mi,  docs: 1 Mi)
    log_segment_size_max: 256MiB # 256 Mi (helm: 256Mi, docs: null)
    compacted_log_segment_size: 128MiB # 128 Mi (helm: 512Mi, docs: 256 Mi)
    max_compacted_log_segment_size: 512MiB # 512 Mi (helm: 512Mi, docs: 5 Gi)
    append_chunk_size: 64KiB # 64 Ki  (helm: NA,    docs: 16 Ki)
    kafka_batch_max_bytes: 1MiB # 1 mb
    topic_partitions_per_shard: 1000 # 1000 (helm: 1000,    docs: 7000)
    kafka_connection_rate_limit: 1000
    group_topic_partitions: 16
    delete_retention_ms: -1ms
    retention_bytes: -1  # <--- NOT WORKING 
tuning:
  tune_aio_events: true
  tune_clocksource: true
  tune_ballast_file: true
  ballast_file_path: /var/lib/redpanda/data/ballast
  ballast_file_size: 10GiB
  well_known_io: gcp:n2-highmem-64:ssd
